import { EstadoCita } from "@prisma/client";



export const citas = [
  {
    id_cliente: 1,
    id_mascota: 1,
    id_servicio: 1,
    id_sucursal: 1,
    fecha_cita: new Date('2024-06-18T14:00:00Z'),
    hora_cita: new Date('2024-06-18T14:00:00Z'),
    estado: EstadoCita.Pendiente,
    observaciones: 'Primera cita',
    motivo: 'Vacunación',
    condicion: 'Ninguna',
    vacunas: 'Todas al día',
  },
  {
    id_cliente: 2,
    id_mascota: 2,
    id_servicio: 2,
    id_sucursal: 2,
    fecha_cita: new Date('2024-06-19T15:00:00Z'),
    hora_cita: new Date('2024-06-19T15:00:00Z'),
    estado: EstadoCita.Confirmada,
    observaciones: 'Control general',
    motivo: 'Chequeo anual',
    condicion: 'Alergia a pulgas',
    vacunas: 'Faltan refuerzos',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.Completada,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.Confirmada,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.No_asistio,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.Pendiente,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.Reprogramada,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  },
  {
    id_cliente: 3,
    id_mascota: 3,
    id_servicio: 3,
    id_sucursal: 3,
    fecha_cita: new Date('2024-06-20T16:00:00Z'),
    hora_cita: new Date('2024-06-20T16:00:00Z'),
    estado: EstadoCita.Cancelada,
    observaciones: 'Revisión completa',
    motivo: 'Desparasitación',
    condicion: 'Problemas digestivos',
    vacunas: 'Al día',
  }
];
