export const productos = [
  {
    nombre: 'Alimento para perros',
    descripcion: 'Alimento premium para perros adultos',
    id_categoria: 1,
    precio: 25000,
    Marca: 'DogFood',
    Tipo_mascota: 'Perro',
  },
  {
    nombre: 'Arena para gatos',
    descripcion: 'Arena sanitaria aglomerante',
    id_categoria: 2,
    precio: 15000,
    Marca: 'CatLitter',
    Tipo_mascota: 'Gato',
  },
  {
    nombre: 'Juguete para mascotas',
    descripcion: 'Juguete interactivo para perros y gatos',
    id_categoria: 3,
    precio: 10000,
    Marca: 'PetToy',
    Tipo_mascota: 'General',
  },
  {
    nombre: 'Collar antipulgas',
    descripcion: 'Collar repelente de pulgas para perros',
    id_categoria: 1,
    precio: 12000,
    Marca: 'AntiFlea',
    Tipo_mascota: 'Perro',
  },
  {
    nombre: 'Rascador para gatos',
    descripcion: 'Rascador de gatos con múltiples niveles',
    id_categoria: 2,
    precio: 20000,
    Marca: 'CatScratcher',
    Tipo_mascota: 'Gato',
  },
  {
    nombre: 'Caseta para perros',
    descripcion: 'Caseta grande para perros',
    id_categoria: 1,
    precio: 50000,
    Marca: 'DogHouse',
    Tipo_mascota: 'Perro',
  },
  {
    nombre: 'Transportadora para mascotas',
    descripcion: 'Transportadora para mascotas de tamaño mediano',
    id_categoria: 3,
    precio: 35000,
    Marca: 'PetCarrier',
    Tipo_mascota: 'General',
  },
  {
    nombre: 'Shampoo para perros',
    descripcion: 'Shampoo especial para el cuidado del pelaje',
    id_categoria: 1,
    precio: 8000,
    Marca: 'DogShampoo',
    Tipo_mascota: 'Perro',
  },
  {
    nombre: 'Juguete interactivo para gatos',
    descripcion: 'Juguete electrónico que mantiene a los gatos entretenidos',
    id_categoria: 2,
    precio: 18000,
    Marca: 'CatToy',
    Tipo_mascota: 'Gato',
  },
  {
    nombre: 'Arnés para perros',
    descripcion: 'Arnés cómodo y ajustable para perros',
    id_categoria: 1,
    precio: 22000,
    Marca: 'DogHarness',
    Tipo_mascota: 'Perro',
  },
  ];