export const productos = [
  {
    nombre: "Alimento para Perros",
    descripcion: "Alimento seco para perros adultos",
    id_categoria: 1,
    precio: 25000.0,
    Marca: "Purina",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Alimento para Gatos",
    descripcion: "Alimento seco para gatos adultos",
    id_categoria: 1,
    precio: 22000.0,
    Marca: "Whiskas",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Juguete de Pelota",
    descripcion: "Pelota de goma para perros",
    id_categoria: 2,
    precio: 5000.0,
    Marca: "Kong",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Rascador para Gatos",
    descripcion: "Rascador de sisal para gatos",
    id_categoria: 2,
    precio: 15000.0,
    Marca: "Petstages",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Shampoo para Perros",
    descripcion: "Shampoo antipulgas para perros",
    id_categoria: 3,
    precio: 8000.0,
    Marca: "Hartz",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Arenas Sanitarias para Gatos",
    descripcion: "Arena aglomerante para gatos",
    id_categoria: 3,
    precio: 10000.0,
    Marca: "Tidy Cats",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Antipulgas",
    descripcion: "Collar antipulgas para perros",
    id_categoria: 4,
    precio: 18000.0,
    Marca: "Seresto",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Antipulgas para Gatos",
    descripcion: "Pipeta antipulgas para gatos",
    id_categoria: 4,
    precio: 15000.0,
    Marca: "Frontline",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Collar para Perros",
    descripcion: "Collar ajustable para perros",
    id_categoria: 5,
    precio: 12000.0,
    Marca: "Rogz",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Arnés para Gatos",
    descripcion: "Arnés y correa para gatos",
    id_categoria: 5,
    precio: 9000.0,
    Marca: "Catit",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Jersey para Perros",
    descripcion: "Jersey de lana para perros pequeños",
    id_categoria: 6,
    precio: 20000.0,
    Marca: "Pet Life",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Camiseta para Gatos",
    descripcion: "Camiseta de algodón para gatos",
    id_categoria: 6,
    precio: 18000.0,
    Marca: "Pawz",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Transportadora para Perros",
    descripcion: "Transportadora mediana para perros",
    id_categoria: 7,
    precio: 45000.0,
    Marca: "Petmate",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Transportadora para Gatos",
    descripcion: "Transportadora pequeña para gatos",
    id_categoria: 7,
    precio: 40000.0,
    Marca: "Petmate",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Cama para Perros",
    descripcion: "Cama acolchada para perros grandes",
    id_categoria: 8,
    precio: 35000.0,
    Marca: "Best Friends",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Cama para Gatos",
    descripcion: "Cama tipo cueva para gatos",
    id_categoria: 8,
    precio: 30000.0,
    Marca: "Kitty City",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Correa Retráctil",
    descripcion: "Correa retráctil para perros medianos",
    id_categoria: 9,
    precio: 25000.0,
    Marca: "Flexi",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Correa Simple",
    descripcion: "Correa simple para gatos",
    id_categoria: 9,
    precio: 10000.0,
    Marca: "Petsafe",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Collar con Placa",
    descripcion: "Collar con placa de identificación para perros",
    id_categoria: 10,
    precio: 15000.0,
    Marca: "GoTags",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Collar con Campana",
    descripcion: "Collar con campana para gatos",
    id_categoria: 10,
    precio: 8000.0,
    Marca: "Blueberry",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Arena para Gatos",
    descripcion: "Arena perfumada para gatos",
    id_categoria: 11,
    precio: 12000.0,
    Marca: "Fresh Step",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Filtro de Agua",
    descripcion: "Filtro de agua para bebedero de perros",
    id_categoria: 12,
    precio: 15000.0,
    Marca: "Drinkwell",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Pecera Pequeña",
    descripcion: "Pecera pequeña de vidrio",
    id_categoria: 13,
    precio: 30000.0,
    Marca: "Marina",
    Tipo_mascota: "Peces",
  },
  {
    nombre: "Terrario",
    descripcion: "Terrario para reptiles",
    id_categoria: 14,
    precio: 50000.0,
    Marca: "Exo Terra",
    Tipo_mascota: "Reptiles",
  },
  {
    nombre: "Jaula para Pájaros",
    descripcion: "Jaula mediana para pájaros",
    id_categoria: 15,
    precio: 25000.0,
    Marca: "Prevue",
    Tipo_mascota: "Pájaros",
  },
  {
    nombre: "Comedero de Acero",
    descripcion: "Comedero de acero inoxidable para perros",
    id_categoria: 16,
    precio: 10000.0,
    Marca: "Loving Pets",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Bebedero Automático",
    descripcion: "Bebedero automático para gatos",
    id_categoria: 16,
    precio: 15000.0,
    Marca: "Catit",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Aceite de Salmón",
    descripcion: "Suplemento de aceite de salmón para perros",
    id_categoria: 17,
    precio: 20000.0,
    Marca: "Grizzly",
    Tipo_mascota: "Perro",
  },
  {
    nombre: "Multivitamínico",
    descripcion: "Suplemento multivitamínico para gatos",
    id_categoria: 17,
    precio: 18000.0,
    Marca: "Nutri-Vet",
    Tipo_mascota: "Gato",
  },
  {
    nombre: "Termómetro Digital",
    descripcion: "Termómetro digital para acuarios",
    id_categoria: 18,
    precio: 12000.0,
    Marca: "AquaTop",
    Tipo_mascota: "Peces",
  },
  {
    nombre: "Estetoscopio Veterinario",
    descripcion: "Estetoscopio para uso veterinario",
    id_categoria: 19,
    precio: 35000.0,
    Marca: "3M Littmann",
    Tipo_mascota: "Todos",
  },
  {
    nombre: "Libro de Entrenamiento",
    descripcion: "Guía de entrenamiento para perros",
    id_categoria: 20,
    precio: 8000.0,
    Marca: "Cesar Millan",
    Tipo_mascota: "Perro",
  },
];
