export const servicios = [
  {
    nombre: "Consulta General",
    descripcion: "Consulta veterinaria general",
    tarifa: 15000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "General",
  },
  {
    nombre: "Vacunación",
    descripcion: "Aplicación de vacunas",
    tarifa: 10000.0,
    tiempo_servicio: new Date("2024-01-01T00:15:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Vacunas",
  },
  {
    nombre: "Desparasitación",
    descripcion: "Desparasitación interna y externa",
    tarifa: 12500.0,
    tiempo_servicio: new Date("2024-01-01T00:20:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Desparasitación",
  },
  {
    nombre: "Consulta Especializada",
    descripcion: "Consulta con especialista",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Especialista",
  },
  {
    nombre: "Cirugía Menor",
    descripcion: "Cirugía de menor complejidad",
    tarifa: 50000.0,
    tiempo_servicio: new Date("2024-01-01T02:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Cirugía",
  },
  {
    nombre: "Cirugía Mayor",
    descripcion: "Cirugía de alta complejidad",
    tarifa: 100000.0,
    tiempo_servicio: new Date("2024-01-01T04:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Cirugía",
  },
  {
    nombre: "Odontología",
    descripcion: "Limpieza dental y tratamiento",
    tarifa: 30000.0,
    tiempo_servicio: new Date("2024-01-01T01:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Odontología",
  },
  {
    nombre: "Radiografía",
    descripcion: "Servicio de radiografía",
    tarifa: 20000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Diagnóstico",
  },
  {
    nombre: "Ecografía",
    descripcion: "Servicio de ecografía",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Diagnóstico",
  },
  {
    nombre: "Análisis de Sangre",
    descripcion: "Análisis completo de sangre",
    tarifa: 17500.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Laboratorio",
  },
  {
    nombre: "Hospitalización",
    descripcion: "Cuidado en hospitalización",
    tarifa: 75000.0,
    tiempo_servicio: new Date("2024-01-01T24:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Hospitalización",
  },
  {
    nombre: "Peluquería Canina",
    descripcion: "Corte de pelo y baño para perros",
    tarifa: 15000.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Perros",
    Especialidad: "Peluquería",
  },
  {
    nombre: "Peluquería Felina",
    descripcion: "Corte de pelo y baño para gatos",
    tarifa: 17500.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Gatos",
    Especialidad: "Peluquería",
  },
  {
    nombre: "Terapia Física",
    descripcion: "Terapia de rehabilitación",
    tarifa: 22500.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Rehabilitación",
  },
  {
    nombre: "Consulta Dermatológica",
    descripcion: "Tratamiento de problemas de piel",
    tarifa: 20000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Dermatología",
  },
  {
    nombre: "Consulta Cardiológica",
    descripcion: "Tratamiento de problemas cardíacos",
    tarifa: 30000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Cardiología",
  },
  {
    nombre: "Consulta Neurológica",
    descripcion: "Tratamiento de problemas neurológicos",
    tarifa: 35000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Neurología",
  },
  {
    nombre: "Consulta Oftalmológica",
    descripcion: "Tratamiento de problemas oculares",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Oftalmología",
  },
  {
    nombre: "Consulta Oncológica",
    descripcion: "Tratamiento de cáncer",
    tarifa: 40000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Oncología",
  },
  {
    nombre: "Consulta Ortopédica",
    descripcion: "Tratamiento de problemas ortopédicos",
    tarifa: 35000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Ortopedia",
  },
  {
    nombre: "Consulta de Comportamiento",
    descripcion: "Tratamiento de problemas de comportamiento",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Comportamiento",
  },
  {
    nombre: "Consulta Nutricional",
    descripcion: "Asesoramiento nutricional",
    tarifa: 20000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Nutrición",
  },
  {
    nombre: "Terapia de Acupuntura",
    descripcion: "Tratamiento con acupuntura",
    tarifa: 30000.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Acupuntura",
  },
  {
    nombre: "Fisioterapia",
    descripcion: "Rehabilitación física",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Fisioterapia",
  },
  {
    nombre: "Hidroterapia",
    descripcion: "Terapia con agua",
    tarifa: 35000.0,
    tiempo_servicio: new Date("2024-01-01T01:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Hidroterapia",
  },
  {
    nombre: "Consulta de Reproducción",
    descripcion: "Tratamiento de problemas reproductivos",
    tarifa: 30000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Reproducción",
  },
  {
    nombre: "Consultoría de Bienestar Animal",
    descripcion: "Asesoramiento sobre bienestar animal",
    tarifa: 20000.0,
    tiempo_servicio: new Date("2024-01-01T00:30:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Bienestar",
  },
  {
    nombre: "Emergencias",
    descripcion: "Atención de emergencias veterinarias",
    tarifa: 50000.0,
    tiempo_servicio: new Date("2024-01-01T02:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Emergencias",
  },
  {
    nombre: "Ultrasonido",
    descripcion: "Servicio de ultrasonido",
    tarifa: 25000.0,
    tiempo_servicio: new Date("2024-01-01T00:45:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Diagnóstico",
  },
  {
    nombre: "Servicio de Guardería",
    descripcion: "Cuidado diario de mascotas",
    tarifa: 10000.0,
    tiempo_servicio: new Date("2024-01-01T08:00:00Z"),
    Tipo_mascota: "Todos",
    Especialidad: "Guardería",
  },
];
