export const sucursales = [
  {
    nombre: "Sucursal Central",
    descripcion: "Sucursal principal en el centro de la ciudad",
    telefono: "555-0101",
    direccion: "Av. Principal 123, Centro",
    correo_electronico: "central@vetpet.com",
  },
  {
    nombre: "Sucursal Norte",
    descripcion: "Sucursal en la zona norte",
    telefono: "555-0202",
    direccion: "Calle Norte 456, Norte",
    correo_electronico: "norte@vetpet.com",
  },
  {
    nombre: "Sucursal Sur",
    descripcion: "Sucursal en la zona sur",
    telefono: "555-0303",
    direccion: "Calle Sur 789, Sur",
    correo_electronico: "sur@vetpet.com",
  },
  {
    nombre: "Sucursal Este",
    descripcion: "Sucursal en la zona este",
    telefono: "555-0404",
    direccion: "Av. Este 101, Este",
    correo_electronico: "este@vetpet.com",
  },
  {
    nombre: "Sucursal Oeste",
    descripcion: "Sucursal en la zona oeste",
    telefono: "555-0505",
    direccion: "Av. Oeste 202, Oeste",
    correo_electronico: "oeste@vetpet.com",
  },
  {
    nombre: "Sucursal Centro Comercial",
    descripcion: "Sucursal en el centro comercial",
    telefono: "555-0606",
    direccion: "Centro Comercial ABC, Local 3",
    correo_electronico: "cc@vetpet.com",
  },
  {
    nombre: "Sucursal Playa",
    descripcion: "Sucursal en la zona de la playa",
    telefono: "555-0707",
    direccion: "Av. Playa 303, Playa",
    correo_electronico: "playa@vetpet.com",
  },
  {
    nombre: "Sucursal Montaña",
    descripcion: "Sucursal en la zona montañosa",
    telefono: "555-0808",
    direccion: "Calle Montaña 404, Montaña",
    correo_electronico: "montana@vetpet.com",
  },
  {
    nombre: "Sucursal Aeropuerto",
    descripcion: "Sucursal cerca del aeropuerto",
    telefono: "555-0909",
    direccion: "Av. Aeropuerto 505, Aeropuerto",
    correo_electronico: "aeropuerto@vetpet.com",
  },
  {
    nombre: "Sucursal Parque",
    descripcion: "Sucursal cerca del parque central",
    telefono: "555-1010",
    direccion: "Calle Parque 606, Parque",
    correo_electronico: "parque@vetpet.com",
  },
];
