import { Rol } from "@prisma/client";

export const usuarios = [
  // Sucursal 1
  {
    nombre: "Juan Perez",
    telefono: "555-1111",
    correo_electronico: "juan.perez@vetpet.com",
    direccion: "Calle Falsa 123",
    fecha_nacimiento: new Date("1980-01-01"),
    contrasena: "contrasena1",
    rol: Rol.cliente,
    id_sucursal: 1,
  },
  //id 2
  {
    nombre: "Maria Gomez",
    telefono: "555-1112",
    correo_electronico: "maria.gomez@vetpet.com",
    direccion: "Calle Verdadera 456",
    fecha_nacimiento: new Date("1990-02-02"),
    contrasena: "contrasena2",
    rol: Rol.encargado,
    id_sucursal: 1,
  },
  {
    nombre: "Pedro Martinez",
    telefono: "555-1113",
    correo_electronico: "pedro.martinez@vetpet.com",
    direccion: "Avenida Siempre Viva 789",
    fecha_nacimiento: new Date("1985-03-03"),
    contrasena: "contrasena3",
    rol: Rol.administrador,
    id_sucursal: 1,
  },

  // Sucursal 2
  {
    nombre: "Luisa Fernandez",
    telefono: "555-1121",
    correo_electronico: "luisa.fernandez@vetpet.com",
    direccion: "Calle Luna 101",
    fecha_nacimiento: new Date("1992-04-04"),
    contrasena: "contrasena4",
    rol: Rol.cliente,
    id_sucursal: 2,
  },
  //id 5
  {
    nombre: "Carlos Sanchez",
    telefono: "555-1122",
    correo_electronico: "carlos.sanchez@vetpet.com",
    direccion: "Calle Sol 202",
    fecha_nacimiento: new Date("1988-05-05"),
    contrasena: "contrasena5",
    rol: Rol.encargado,
    id_sucursal: 2,
  },
  {
    nombre: "Ana Lopez",
    telefono: "555-1123",
    correo_electronico: "ana.lopez@vetpet.com",
    direccion: "Calle Estrella 303",
    fecha_nacimiento: new Date("1982-06-06"),
    contrasena: "contrasena6",
    rol: Rol.administrador,
    id_sucursal: 2,
  },

  // Sucursal 3
  {
    nombre: "Miguel Rodriguez",
    telefono: "555-1131",
    correo_electronico: "miguel.rodriguez@vetpet.com",
    direccion: "Calle Mar 404",
    fecha_nacimiento: new Date("1975-07-07"),
    contrasena: "contrasena7",
    rol: Rol.cliente,
    id_sucursal: 3,
  },
  //id 8
  {
    nombre: "Sofia Diaz",
    telefono: "555-1132",
    correo_electronico: "sofia.diaz@vetpet.com",
    direccion: "Calle Tierra 505",
    fecha_nacimiento: new Date("1995-08-08"),
    contrasena: "contrasena8",
    rol: Rol.encargado,
    id_sucursal: 3,
  },
  {
    nombre: "Pablo Torres",
    telefono: "555-1133",
    correo_electronico: "pablo.torres@vetpet.com",
    direccion: "Calle Aire 606",
    fecha_nacimiento: new Date("1981-09-09"),
    contrasena: "contrasena9",
    rol: Rol.administrador,
    id_sucursal: 3,
  },

  // Sucursal 4
  {
    nombre: "Laura Ramirez",
    telefono: "555-1141",
    correo_electronico: "laura.ramirez@vetpet.com",
    direccion: "Calle Fuego 707",
    fecha_nacimiento: new Date("1983-10-10"),
    contrasena: "contrasena10",
    rol: Rol.cliente,
    id_sucursal: 4,
  },
  {
    nombre: "David Morales",
    telefono: "555-1142",
    correo_electronico: "david.morales@vetpet.com",
    direccion: "Calle Agua 808",
    fecha_nacimiento: new Date("1979-11-11"),
    contrasena: "contrasena11",
    rol: Rol.encargado,
    id_sucursal: 4,
  },
  {
    nombre: "Carolina Mendez",
    telefono: "555-1143",
    correo_electronico: "carolina.mendez@vetpet.com",
    direccion: "Calle Metal 909",
    fecha_nacimiento: new Date("1987-12-12"),
    contrasena: "contrasena12",
    rol: Rol.administrador,
    id_sucursal: 4,
  },

  // Sucursal 5
  {
    nombre: "Andres Flores",
    telefono: "555-1151",
    correo_electronico: "andres.flores@vetpet.com",
    direccion: "Calle Madera 1010",
    fecha_nacimiento: new Date("1991-01-01"),
    contrasena: "contrasena13",
    rol: Rol.cliente,
    id_sucursal: 5,
  },
  {
    nombre: "Paula Castro",
    telefono: "555-1152",
    correo_electronico: "paula.castro@vetpet.com",
    direccion: "Calle Piedra 1111",
    fecha_nacimiento: new Date("1989-02-02"),
    contrasena: "contrasena14",
    rol: Rol.encargado,
    id_sucursal: 5,
  },
  {
    nombre: "Jorge Suarez",
    telefono: "555-1153",
    correo_electronico: "jorge.suarez@vetpet.com",
    direccion: "Calle Hierro 1212",
    fecha_nacimiento: new Date("1986-03-03"),
    contrasena: "contrasena15",
    rol: Rol.administrador,
    id_sucursal: 5,
  },

  // Sucursal 6
  {
    nombre: "Gabriela Vega",
    telefono: "555-1161",
    correo_electronico: "gabriela.vega@vetpet.com",
    direccion: "Calle Cristal 1313",
    fecha_nacimiento: new Date("1994-04-04"),
    contrasena: "contrasena16",
    rol: Rol.cliente,
    id_sucursal: 6,
  },
  {
    nombre: "Hugo Varela",
    telefono: "555-1162",
    correo_electronico: "hugo.varela@vetpet.com",
    direccion: "Calle Oro 1414",
    fecha_nacimiento: new Date("1984-05-05"),
    contrasena: "contrasena17",
    rol: Rol.encargado,
    id_sucursal: 6,
  },
  {
    nombre: "Monica Reyes",
    telefono: "555-1163",
    correo_electronico: "monica.reyes@vetpet.com",
    direccion: "Calle Plata 1515",
    fecha_nacimiento: new Date("1990-06-06"),
    contrasena: "contrasena18",
    rol: Rol.administrador,
    id_sucursal: 6,
  },

  // Sucursal 7
  {
    nombre: "Luis Gil",
    telefono: "555-1171",
    correo_electronico: "luis.gil@vetpet.com",
    direccion: "Calle Bronce 1616",
    fecha_nacimiento: new Date("1981-07-07"),
    contrasena: "contrasena19",
    rol: Rol.cliente,
    id_sucursal: 7,
  },
  {
    nombre: "Valentina Ponce",
    telefono: "555-1172",
    correo_electronico: "valentina.ponce@vetpet.com",
    direccion: "Calle Cobre 1717",
    fecha_nacimiento: new Date("1988-08-08"),
    contrasena: "contrasena20",
    rol: Rol.encargado,
    id_sucursal: 7,
  },
  {
    nombre: "Santiago Guzman",
    telefono: "555-1173",
    correo_electronico: "santiago.guzman@vetpet.com",
    direccion: "Calle Zinc 1818",
    fecha_nacimiento: new Date("1978-09-09"),
    contrasena: "contrasena21",
    rol: Rol.administrador,
    id_sucursal: 7,
  },

  // Sucursal 8
  {
    nombre: "Lorena Ortiz",
    telefono: "555-1181",
    correo_electronico: "lorena.ortiz@vetpet.com",
    direccion: "Calle Titanio 1919",
    fecha_nacimiento: new Date("1992-10-10"),
    contrasena: "contrasena22",
    rol: Rol.cliente,
    id_sucursal: 8,
  },
  {
    nombre: "Adrian Maldonado",
    telefono: "555-1182",
    correo_electronico: "adrian.maldonado@vetpet.com",
    direccion: "Calle Platino 2020",
    fecha_nacimiento: new Date("1983-11-11"),
    contrasena: "contrasena23",
    rol: Rol.encargado,
    id_sucursal: 8,
  },
  {
    nombre: "Daniela Cabrera",
    telefono: "555-1183",
    correo_electronico: "daniela.cabrera@vetpet.com",
    direccion: "Calle Cuarzo 2121",
    fecha_nacimiento: new Date("1985-12-12"),
    contrasena: "contrasena24",
    rol: Rol.administrador,
    id_sucursal: 8,
  },

  // Sucursal 9
  {
    nombre: "Ricardo Guerrero",
    telefono: "555-1191",
    correo_electronico: "ricardo.guerrero@vetpet.com",
    direccion: "Calle Diamante 2222",
    fecha_nacimiento: new Date("1987-01-01"),
    contrasena: "contrasena25",
    rol: Rol.cliente,
    id_sucursal: 9,
  },
  {
    nombre: "Elena Acosta",
    telefono: "555-1192",
    correo_electronico: "elena.acosta@vetpet.com",
    direccion: "Calle Rubi 2323",
    fecha_nacimiento: new Date("1986-02-02"),
    contrasena: "contrasena26",
    rol: Rol.encargado,
    id_sucursal: 9,
  },
  {
    nombre: "Francisco Villalobos",
    telefono: "555-1193",
    correo_electronico: "francisco.villalobos@vetpet.com",
    direccion: "Calle Esmeralda 2424",
    fecha_nacimiento: new Date("1991-03-03"),
    contrasena: "contrasena27",
    rol: Rol.administrador,
    id_sucursal: 9,
  },

  // Sucursal 10
  {
    nombre: "Ines Flores",
    telefono: "555-1201",
    correo_electronico: "ines.flores@vetpet.com",
    direccion: "Calle Zafiro 2525",
    fecha_nacimiento: new Date("1980-04-04"),
    contrasena: "contrasena28",
    rol: Rol.cliente,
    id_sucursal: 10,
  },
  {
    nombre: "Oscar Castillo",
    telefono: "555-1202",
    correo_electronico: "oscar.castillo@vetpet.com",
    direccion: "Calle Topacio 2626",
    fecha_nacimiento: new Date("1979-05-05"),
    contrasena: "contrasena29",
    rol: Rol.encargado,
    id_sucursal: 10,
  },
  {
    nombre: "Patricia Rios",
    telefono: "555-1203",
    correo_electronico: "patricia.rios@vetpet.com",
    direccion: "Calle Perla 2727",
    fecha_nacimiento: new Date("1984-06-06"),
    contrasena: "contrasena30",
    rol: Rol.administrador,
    id_sucursal: 10,
  },
  //usuarios sin sucursal

{
  nombre: "Pepe Gomez",
  telefono: "555-1112",
  correo_electronico: "Pepe.gomez@vetpet.com",
  direccion: "Calle Verdadera 456",
  fecha_nacimiento: new Date("1990-02-02"),
  contrasena: "contrasena2",
  rol: Rol.encargado,
  id_sucursal: null,
},

{
  nombre: "Rosita Gomez",
  telefono: "555-1112",
  correo_electronico: "Rosita.gomez@vetpet.com",
  direccion: "Calle Verdadera 456",
  fecha_nacimiento: new Date("1990-02-02"),
  contrasena: "contrasena2",
  rol: Rol.encargado,
  id_sucursal: null,
},

{
  nombre: "Roma Gomez",
  telefono: "555-1112",
  correo_electronico: "Roma.gomez@vetpet.com",
  direccion: "Calle Verdadera 456",
  fecha_nacimiento: new Date("1990-02-02"),
  contrasena: "contrasena2",
  rol: Rol.encargado,
  id_sucursal: null,
},
];


